// <auto-generated />
namespace Thinktecture.IdentityServer.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddExternalProvidersOAuthMembershipClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExternalProvidersOAuthMembershipClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201302241656164_AddExternalProvidersOAuthMembershipClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
